// <auto-generated />
using System;
using Education_assistant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education_assistant.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250629121003_edithocba")]
    partial class edithocba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Education_assistant.Models.BoMon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_bo_mon");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("bo_mon");
                });

            modelBuilder.Entity("Education_assistant.Models.ChiTietChuongTrinhDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoMonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bo_mon_id");

                    b.Property<Guid?>("ChuongTrinhDaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chuong_trinh_dao_tao_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DiemTichLuy")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("diem_tich_luy");

                    b.Property<int>("HocKy")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky");

                    b.Property<int?>("LoaiMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("loai_mon_hoc");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BoMonId");

                    b.HasIndex("ChuongTrinhDaoTaoId");

                    b.HasIndex("MonHocId");

                    b.ToTable("chi_tiet_chuong_trinh_dao_tao");
                });

            modelBuilder.Entity("Education_assistant.Models.ChiTietLopHocPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_chuyen_can");

                    b.Property<decimal?>("DiemThi1")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_thi_1");

                    b.Property<decimal?>("DiemThi2")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_thi_2");

                    b.Property<decimal?>("DiemTongKet1")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_tong_ket_1");

                    b.Property<decimal?>("DiemTongKet2")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_tong_ket_2");

                    b.Property<decimal?>("DiemTrungBinh")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_trung_binh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<int>("HocKy")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ky");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<DateTime?>("NgayLuuDiem")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_luu_diem");

                    b.Property<DateTime?>("NgayNopDiem")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_nop_diem");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai_diem");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("chi_tiet_lop_hoc_phan");
                });

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("Khoa")
                        .HasColumnType("int")
                        .HasColumnName("khoa");

                    b.Property<int?>("LoaiChuonTrinhDaoTao")
                        .HasColumnType("int")
                        .HasColumnName("loai_chuong_trinh_dao_tao");

                    b.Property<string>("MaChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_chuong_trinh");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<Guid?>("NganhId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nganh_id");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_chuong_trinh");

                    b.Property<string>("ThoiGianDaoTao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("thoi_gian_dao_tao");

                    b.Property<int>("TongSoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("tong_so_tin_chi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NganhId");

                    b.ToTable("chuong_trinh_dao_tao");
                });

            modelBuilder.Entity("Education_assistant.Models.DangKyMonHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("Diem")
                        .HasPrecision(2, 2)
                        .HasColumnType("decimal(2,2)")
                        .HasColumnName("diem");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<DateTime>("NgayDangKyHoc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang_ky_hoc");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("dang_ky_mon_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("longtext")
                        .HasColumnName("anh_dai_dien");

                    b.Property<Guid?>("BoMonId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bo_mon_id");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cccd");

                    b.Property<int?>("ChucVu")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("chuc_vu");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("chuyen_nganh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime?>("NgayVaoTruong")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_vao_truong");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tai_khoan_id");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai_giang_vien");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trinh_do");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BoMonId");

                    b.HasIndex("KhoaId");

                    b.HasIndex("TaiKhoanId")
                        .IsUnique();

                    b.ToTable("giang_vien");
                });

            modelBuilder.Entity("Education_assistant.Models.HocBa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChiTietChuongTrinhDaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chi_tiet_chuong_trinh_dao_tao_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiemTongKet")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("diem_tong_ket");

                    b.Property<int?>("KetQua")
                        .HasColumnType("int")
                        .HasColumnName("ket_qua");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietChuongTrinhDaoTaoId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("hoc_ba");
                });

            modelBuilder.Entity("Education_assistant.Models.Khoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_khoa");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViTriPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_tri_phong");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.LichBieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<Guid?>("PhongHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("phong_hoc_id");

                    b.Property<int>("Thu")
                        .HasColumnType("int")
                        .HasColumnName("thu");

                    b.Property<int>("TietBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tiet_bat_dau");

                    b.Property<int>("TietKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("tiet_ket_thuc");

                    b.Property<Guid?>("TuanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tuan_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("PhongHocId");

                    b.HasIndex("TuanId");

                    b.ToTable("lich_bieu");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_lop_hoc");

                    b.Property<int>("NamHoc")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("nam_hoc");

                    b.Property<Guid?>("NganhId")
                        .HasColumnType("char(36)")
                        .HasColumnName("nganh_id");

                    b.Property<int>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("si_so");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("NganhId");

                    b.ToTable("lop_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<int?>("Loai")
                        .HasColumnType("int")
                        .HasColumnName("loai-lop");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<Guid>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<int>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("si_so");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("MonHocId");

                    b.ToTable("lop_hoc_phan");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_mon_hoc");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_mon_hoc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("mon_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.Nganh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_nganh");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_nganh");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("nganh");
                });

            modelBuilder.Entity("Education_assistant.Models.PhongHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("LoaiPhongHoc")
                        .HasColumnType("int")
                        .HasColumnName("loai_phong");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("suc_chua");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_phong");

                    b.Property<string>("ToaNha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("toa_nha");

                    b.Property<int?>("TrangThaiPhongHoc")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("phong_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<Guid?>("LopHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_id");

                    b.Property<string>("MSSV")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mssv");

                    b.Property<DateTime>("NgayNhapHoc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_nhap_hoc");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTotNghiep")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tot_nghiep");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<int?>("TinhTrangHocTap")
                        .HasColumnType("int")
                        .HasColumnName("tinh_trang_hoc_tap");

                    b.Property<int?>("TrangThaiSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai_sinh_vien");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.ToTable("sinh_vien");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVienChuongTrinhDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChuongTrinhDaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chuong_trinh_dao_tao_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhDaoTaoId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("sinh_vien_chuong_trinh_dao_tao");
                });

            modelBuilder.Entity("Education_assistant.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang_nhap");

                    b.Property<int?>("LoaiTaiKhoan")
                        .HasColumnType("int")
                        .HasColumnName("loai_tai_khoan");

                    b.Property<int?>("LockTime")
                        .HasColumnType("int")
                        .HasColumnName("khoa_dang_nhap");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("ResetPassword")
                        .HasColumnType("longtext")
                        .HasColumnName("reset-password");

                    b.Property<DateTime?>("ResetPasswordExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset-password-expires");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset_expires");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trang_thai");

                    b.Property<int?>("TimeLogin")
                        .HasColumnType("int")
                        .HasColumnName("so_lan_dang_nhap");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tai_khoan");
                });

            modelBuilder.Entity("Education_assistant.Models.Truong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("truong");
                });

            modelBuilder.Entity("Education_assistant.Models.Tuan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int")
                        .HasColumnName("nam_hoc");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int>("SoTuan")
                        .HasColumnType("int")
                        .HasColumnName("so_tuan");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tuan");
                });

            modelBuilder.Entity("Education_assistant.Models.BoMon", b =>
                {
                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.ChiTietChuongTrinhDaoTao", b =>
                {
                    b.HasOne("Education_assistant.Models.BoMon", "BoMon")
                        .WithMany("DanhSachChiTietChuongTrinhDaoTao")
                        .HasForeignKey("BoMonId");

                    b.HasOne("Education_assistant.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("DanhSachChiTietChuongTrinhDaoTao")
                        .HasForeignKey("ChuongTrinhDaoTaoId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachChiTietChuongTrinhDaoTao")
                        .HasForeignKey("MonHocId");

                    b.Navigation("BoMon");

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.ChiTietLopHocPhan", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachChiTietLopHocPhan")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachChiTietLopHocPhan")
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachChiTietLopHocPhan")
                        .HasForeignKey("MonHocId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachChiTietLopHocPhan")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocPhan");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.HasOne("Education_assistant.Models.Nganh", "Nganh")
                        .WithMany("DanhSachChuongTrinhDaoTao")
                        .HasForeignKey("NganhId");

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("Education_assistant.Models.DangKyMonHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachDangKyMonHoc")
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachDangKyMonHoc")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.HasOne("Education_assistant.Models.BoMon", "BoMon")
                        .WithMany("DanhSachGiangVien")
                        .HasForeignKey("BoMonId");

                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachGiangVien")
                        .HasForeignKey("KhoaId");

                    b.HasOne("Education_assistant.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiangVien")
                        .HasForeignKey("Education_assistant.Models.GiangVien", "TaiKhoanId");

                    b.Navigation("BoMon");

                    b.Navigation("Khoa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Education_assistant.Models.HocBa", b =>
                {
                    b.HasOne("Education_assistant.Models.ChiTietChuongTrinhDaoTao", "ChiTietChuongTrinhDaoTao")
                        .WithMany("DanhSachHocBa")
                        .HasForeignKey("ChiTietChuongTrinhDaoTaoId");

                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("ĐanhSachHocBa")
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachHocBa")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("ChiTietChuongTrinhDaoTao");

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.LichBieu", b =>
                {
                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.PhongHoc", "PhongHoc")
                        .WithMany("DanhSachLichBieu")
                        .HasForeignKey("PhongHocId");

                    b.HasOne("Education_assistant.Models.Tuan", "Tuan")
                        .WithMany("DanhSachLichBieu")
                        .HasForeignKey("TuanId");

                    b.Navigation("LopHocPhan");

                    b.Navigation("PhongHoc");

                    b.Navigation("Tuan");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.Nganh", "Nganh")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("NganhId");

                    b.Navigation("GiangVien");

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("KhoaId");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.Nganh", b =>
                {
                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachNganh")
                        .HasForeignKey("KhoaId");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.HasOne("Education_assistant.Models.LopHoc", "LopHoc")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("LopHocId");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVienChuongTrinhDaoTao", b =>
                {
                    b.HasOne("Education_assistant.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("DanhSachSinhVienChuongTrinhDaoTao")
                        .HasForeignKey("ChuongTrinhDaoTaoId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachSinhVienChuongTrinhDaoTao")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.BoMon", b =>
                {
                    b.Navigation("DanhSachChiTietChuongTrinhDaoTao");

                    b.Navigation("DanhSachGiangVien");
                });

            modelBuilder.Entity("Education_assistant.Models.ChiTietChuongTrinhDaoTao", b =>
                {
                    b.Navigation("DanhSachHocBa");
                });

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("DanhSachChiTietChuongTrinhDaoTao");

                    b.Navigation("DanhSachSinhVienChuongTrinhDaoTao");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.Navigation("DanhSachChiTietLopHocPhan");

                    b.Navigation("DanhSachLopHoc");

                    b.Navigation("DanhSachLopHocPhan");
                });

            modelBuilder.Entity("Education_assistant.Models.Khoa", b =>
                {
                    b.Navigation("DanhSachGiangVien");

                    b.Navigation("DanhSachMonHoc");

                    b.Navigation("DanhSachNganh");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.Navigation("DanhSachSinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.Navigation("DanhSachChiTietLopHocPhan");

                    b.Navigation("DanhSachDangKyMonHoc");

                    b.Navigation("ĐanhSachHocBa");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.Navigation("DanhSachChiTietChuongTrinhDaoTao");

                    b.Navigation("DanhSachChiTietLopHocPhan");

                    b.Navigation("DanhSachLopHocPhan");
                });

            modelBuilder.Entity("Education_assistant.Models.Nganh", b =>
                {
                    b.Navigation("DanhSachChuongTrinhDaoTao");

                    b.Navigation("DanhSachLopHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.PhongHoc", b =>
                {
                    b.Navigation("DanhSachLichBieu");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.Navigation("DanhSachChiTietLopHocPhan");

                    b.Navigation("DanhSachDangKyMonHoc");

                    b.Navigation("DanhSachHocBa");

                    b.Navigation("DanhSachSinhVienChuongTrinhDaoTao");
                });

            modelBuilder.Entity("Education_assistant.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Education_assistant.Models.Tuan", b =>
                {
                    b.Navigation("DanhSachLichBieu");
                });
#pragma warning restore 612, 618
        }
    }
}
